<a href="https://colab.research.google.com/github/asdfasdf0311/2023MedicalDataVisualizationCompetition/blob/main/%EB%B3%80%EC%88%98%ED%99%95%EC%9D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#필요한 모듈가져옴
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive #구글 드라이브에 데이터를 저장해서 데이터를 불러왔다.
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dat2011 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2011.CSV', encoding='cp949')
dat2012 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2012.CSV', encoding='cp949')
dat2013 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2013.CSV', encoding='cp949')
dat2014 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2014.CSV', encoding='cp949')
dat2015 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2015.CSV', encoding='cp949')
dat2016 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2016.CSV', encoding='cp949')
dat2017 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2017.CSV', encoding='cp949')

<ipython-input-24-ed318cb094ab>:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  dat2011 = pd.read_csv('/content/drive/MyDrive/dataset/NHIS2011.CSV', encoding='cp949')

In [ ]:
dat2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 34 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   기준년도          1000000 non-null  int64
 1   가입자일련번호       1000000 non-null  int64
 2   성별코드          1000000 non-null  int64
 3   연령대코드(5세단위)   1000000 non-null  int64
 4   시도코드          1000000 non-null  int64
 5   신장(5Cm단위)     1000000 non-null  int64
 6   체중(5Kg 단위)    1000000 non-null  int64
 7   허리둘레          1000000 non-null  int64
 8   시력(좌)         999907 non-null   float64
 9   시력(우)         999897 non-null   float64
 10  청력(좌)         999882 non-null   float64
 11  청력(우)         999879 non-null   float64
 12  수축기혈압         1000000 non-null  int64
 13  이완기혈압         1000000 non-null  int64
 14  식전혈당(공복혈당)    1000000 non-null  int64
 15  총콜레스테롤        1000000 non-null  int64
 16  트리글리세라이드      1000000 non-null  int64
 17  HDL콜레스테롤      1000000 non-null  float64
 18  LDL콜레스테롤      989987 non-null   float64
 19  혈색소           1000000 non-null  float64
 20  요단백           995622 non-null   float64
 21  혈청크레아티닌       1000000 non-null  float64
 22  (혈청지오티)AST    1000000 non-null  int64
 23  (혈청지오티)ALT    1000000 non-null  int64
 24  감마지티피         1000000 non-null  int64
 25  흡연상태          999841 non-null   float64
 26  음주여부          999785 non-null   object
 27  구강검진 수검여부     1000000 non-null  object
 28  치아우식증유무       155208 non-null   object
 29  결손치유무         366828 non-null   object
 30  치아마모증유무       366827 non-null   object
 31  제3대구치(사랑니)이상  286823 non-null   object
 32  치석            366830 non-null   object
 33  데이터공개일자       1000000 non-null  object
dtypes: float64(10), int64(16), object(8)
memory usage: 259.4+ MB

In [ ]:
dat2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 34 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   기준년도          1000000 non-null  int64
 1   가입자일련번호       1000000 non-null  int64
 2   성별코드          1000000 non-null  int64
 3   연령대코드(5세단위)   1000000 non-null  int64
 4   시도코드          1000000 non-null  int64
 5   신장(5Cm단위)     1000000 non-null  int64
 6   체중(5Kg 단위)    1000000 non-null  int64
 7   허리둘레          1000000 non-null  int64
 8   시력(좌)         999853 non-null   float64
 9   시력(우)         999854 non-null   float64
 10  청력(좌)         999864 non-null   float64
 11  청력(우)         999859 non-null   float64
 12  수축기혈압         1000000 non-null  int64
 13  이완기혈압         1000000 non-null  int64
 14  식전혈당(공복혈당)    1000000 non-null  int64
 15  총콜레스테롤        1000000 non-null  int64
 16  트리글리세라이드      1000000 non-null  int64
 17  HDL콜레스테롤      1000000 non-null  int64
 18  LDL콜레스테롤      989017 non-null   float64
 19  혈색소           1000000 non-null  float64
 20  요단백           995568 non-null   float64
 21  혈청크레아티닌       1000000 non-null  float64
 22  (혈청지오티)AST    1000000 non-null  int64
 23  (혈청지오티)ALT    1000000 non-null  int64
 24  감마지티피         1000000 non-null  int64
 25  흡연상태          999908 non-null   float64
 26  음주여부          999903 non-null   object
 27  구강검진 수검여부     1000000 non-null  object
 28  치아우식증유무       384759 non-null   object
 29  결손치유무         384760 non-null   object
 30  치아마모증유무       384761 non-null   object
 31  제3대구치(사랑니)이상  384756 non-null   object
 32  치석            384755 non-null   object
 33  데이터공개일자       1000000 non-null  object
dtypes: float64(9), int64(17), object(8)
memory usage: 259.4+ MB

In [ ]:
dat2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 36 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   기준년도          1000000 non-null  int64
 1   가입자일련번호       1000000 non-null  int64
 2   성별코드          1000000 non-null  int64
 3   연령대코드(5세단위)   1000000 non-null  int64
 4   시도코드          1000000 non-null  int64
 5   신장(5Cm단위)     1000000 non-null  int64
 6   체중(5Kg 단위)    1000000 non-null  int64
 7   허리둘레          1000000 non-null  int64
 8   시력(좌)         999816 non-null   float64
 9   시력(우)         999813 non-null   float64
 10  청력(좌)         999850 non-null   float64
 11  청력(우)         999848 non-null   float64
 12  수축기혈압         1000000 non-null  int64
 13  이완기혈압         1000000 non-null  int64
 14  식전혈당(공복혈당)    1000000 non-null  int64
 15  총콜레스테롤        1000000 non-null  int64
 16  트리글리세라이드      1000000 non-null  int64
 17  HDL콜레스테롤      1000000 non-null  int64
 18  LDL콜레스테롤      994616 non-null   float64
 19  혈색소           1000000 non-null  float64
 20  요단백           995629 non-null   float64
 21  혈청크레아티닌       1000000 non-null  float64
 22  (혈청지오티)AST    1000000 non-null  int64
 23  (혈청지오티)ALT    1000000 non-null  int64
 24  감마지티피         1000000 non-null  int64
 25  흡연상태          999962 non-null   float64
 26  음주여부          999824 non-null   object
 27  구강검진 수검여부     1000000 non-null  object
 28  치아우식증유무       383807 non-null   object
 29  결손치유무         383807 non-null   object
 30  치아마모증유무       383807 non-null   object
 31  제3대구치(사랑니)이상  383807 non-null   object
 32  치석            383807 non-null   object
 33  데이터공개일자       1000000 non-null  object
 34  Unnamed: 34   0 non-null        float64
 35  Unnamed: 35   1 non-null        object
dtypes: float64(10), int64(17), object(9)
memory usage: 274.7+ MB

In [ ]:
dat2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 31 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   기준년도         1000000 non-null  int64
 1   가입자일련번호      1000000 non-null  int64
 2   성별코드         1000000 non-null  int64
 3   연령대코드(5세단위)  1000000 non-null  int64
 4   시도코드         1000000 non-null  int64
 5   신장(5Cm단위)    1000000 non-null  int64
 6   체중(5Kg 단위)   1000000 non-null  int64
 7   허리둘레         1000000 non-null  int64
 8   시력(좌)        999838 non-null   float64
 9   시력(우)        999840 non-null   float64
 10  청력(좌)        999863 non-null   float64
 11  청력(우)        999866 non-null   float64
 12  수축기혈압        1000000 non-null  int64
 13  이완기혈압        1000000 non-null  int64
 14  식전혈당(공복혈당)   1000000 non-null  int64
 15  총콜레스테롤       1000000 non-null  int64
 16  트리글리세라이드     1000000 non-null  int64
 17  HDL콜레스테롤     1000000 non-null  int64
 18  LDL콜레스테롤     995758 non-null   float64
 19  혈색소          1000000 non-null  float64
 20  요단백          995661 non-null   float64
 21  혈청크레아티닌      1000000 non-null  float64
 22  (혈청지오티)AST   1000000 non-null  int64
 23  (혈청지오티)ALT   1000000 non-null  int64
 24  감마지티피        1000000 non-null  int64
 25  흡연상태         999618 non-null   float64
 26  음주여부         999016 non-null   object
 27  구강검진 수검여부    1000000 non-null  object
 28  치아우식증유무      110048 non-null   object
 29  치석유무         382722 non-null   object
 30  데이터 기준일자     1000000 non-null  object
dtypes: float64(9), int64(17), object(5)
memory usage: 236.5+ MB

In [ ]:
dat2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 31 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   기준년도         1000000 non-null  int64
 1   가입자일련번호      1000000 non-null  int64
 2   성별코드         1000000 non-null  int64
 3   연령대코드(5세단위)  1000000 non-null  int64
 4   시도코드         1000000 non-null  int64
 5   신장(5Cm단위)    1000000 non-null  int64
 6   체중(5Kg 단위)   1000000 non-null  int64
 7   허리둘레         1000000 non-null  int64
 8   시력(좌)        999856 non-null   float64
 9   시력(우)        999845 non-null   float64
 10  청력(좌)        999887 non-null   float64
 11  청력(우)        999881 non-null   float64
 12  수축기혈압        1000000 non-null  int64
 13  이완기혈압        1000000 non-null  int64
 14  식전혈당(공복혈당)   1000000 non-null  int64
 15  총콜레스테롤       1000000 non-null  int64
 16  트리글리세라이드     1000000 non-null  int64
 17  HDL콜레스테롤     1000000 non-null  int64
 18  LDL콜레스테롤     996811 non-null   float64
 19  혈색소          1000000 non-null  float64
 20  요단백          995456 non-null   float64
 21  혈청크레아티닌      1000000 non-null  float64
 22  (혈청지오티)AST   1000000 non-null  int64
 23  (혈청지오티)ALT   1000000 non-null  int64
 24  감마지티피        1000000 non-null  int64
 25  흡연상태         999599 non-null   float64
 26  음주여부         999164 non-null   object
 27  구강검진 수검여부    1000000 non-null  object
 28  치아우식증유무      104629 non-null   object
 29  치석유무         381123 non-null   object
 30  데이터 기준일자     1000000 non-null  object
dtypes: float64(9), int64(17), object(5)
memory usage: 236.5+ MB

In [ ]:
dat2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 34 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   기준년도          1000000 non-null  int64
 1   가입자일련번호       1000000 non-null  int64
 2   성별코드          1000000 non-null  int64
 3   연령대코드(5세단위)   1000000 non-null  int64
 4   시도코드          1000000 non-null  int64
 5   신장(5Cm단위)     999103 non-null   float64
 6   체중(5Kg단위)     999103 non-null   float64
 7   허리둘레          999807 non-null   float64
 8   시력(좌)         999700 non-null   float64
 9   시력(우)         999701 non-null   float64
 10  청력(좌)         999734 non-null   float64
 11  청력(우)         999734 non-null   float64
 12  수축기혈압         999912 non-null   float64
 13  이완기혈압         999911 non-null   float64
 14  식전혈당(공복혈당)    999952 non-null   float64
 15  총콜레스테롤        999957 non-null   float64
 16  트리글리세라이드      999956 non-null   float64
 17  HDL콜레스테롤      999953 non-null   float64
 18  LDL콜레스테롤      997369 non-null   float64
 19  혈색소           999947 non-null   float64
 20  요단백           995101 non-null   float64
 21  혈청크레아티닌       999955 non-null   float64
 22  (혈청지오티)AST    999958 non-null   float64
 23  (혈청지오티)ALT    999957 non-null   float64
 24  감마지티피         999957 non-null   float64
 25  흡연상태          999787 non-null   float64
 26  음주여부          0 non-null        float64
 27  구강검진 수검여부     1000000 non-null  object
 28  치아우식증유무       0 non-null        float64
 29  결손치유무         0 non-null        float64
 30  치아마모증유무       0 non-null        float64
 31  제3대구치(사랑니)이상  0 non-null        float64
 32  치석            379984 non-null   object
 33  데이터공개일자       1000000 non-null  object
dtypes: float64(26), int64(5), object(3)
memory usage: 259.4+ MB

In [ ]:
dat2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 34 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   기준년도          1000000 non-null  int64
 1   가입자일련번호       1000000 non-null  int64
 2   성별코드          1000000 non-null  int64
 3   연령대코드(5세단위)   1000000 non-null  int64
 4   시도코드          1000000 non-null  int64
 5   신장(5Cm단위)     1000000 non-null  int64
 6   체중(5Kg단위)     1000000 non-null  int64
 7   허리둘레          999734 non-null   float64
 8   시력(좌)         999817 non-null   float64
 9   시력(우)         999811 non-null   float64
 10  청력(좌)         999842 non-null   float64
 11  청력(우)         999844 non-null   float64
 12  수축기혈압         999981 non-null   float64
 13  이완기혈압         999982 non-null   float64
 14  식전혈당(공복혈당)    999958 non-null   float64
 15  총콜레스테롤        999957 non-null   float64
 16  트리글리세라이드      999955 non-null   float64
 17  HDL콜레스테롤      999956 non-null   float64
 18  LDL콜레스테롤      997088 non-null   float64
 19  혈색소           999948 non-null   float64
 20  요단백           995408 non-null   float64
 21  혈청크레아티닌       999957 non-null   float64
 22  (혈청지오티)AST    999959 non-null   float64
 23  (혈청지오티)ALT    999958 non-null   float64
 24  감마지티피         999958 non-null   float64
 25  흡연상태          999856 non-null   float64
 26  음주여부          999464 non-null   object
 27  구강검진수검여부      1000000 non-null  object
 28  치아우식증유무       0 non-null        float64
 29  결손치유무         0 non-null        float64
 30  치아마모증유무       0 non-null        float64
 31  제3대구치(사랑니)이상  0 non-null        float64
 32  치석            378578 non-null   object
 33  데이터공개일자       1000000 non-null  object
dtypes: float64(23), int64(7), object(4)
memory usage: 259.4+ MB

In [ ]:
dat2011.describe()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태
count,1000000.0,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,999907.000000,999897.000000,...,1000000.00000,1000000.000000,989987.000000,1000000.000000,995622.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,999841.000000
mean,2011.0,500000.500000,1.453735,6.129215,33.428904,162.127850,62.198390,80.245373,0.982922,0.981011,...,132.71711,55.340061,113.647041,14.024697,1.072831,0.996575,25.171788,24.832292,36.455872,1.657889
std,0.0,288675.278932,0.497855,2.787610,12.861787,9.270571,11.683187,9.048950,0.623759,0.620927,...,92.68510,17.874912,41.336313,1.613644,0.390740,1.072771,15.346525,21.225311,48.574831,0.854650
min,2011.0,1.000000,1.000000,1.000000,11.000000,125.000000,25.000000,51.000000,0.100000,0.100000,...,1.00000,1.000000,0.000000,0.400000,1.000000,0.100000,1.000000,1.000000,1.000000,1.000000
25%,2011.0,250000.750000,1.000000,4.000000,26.000000,155.000000,55.000000,74.000000,0.700000,0.700000,...,74.00000,45.000000,90.000000,12.900000,1.000000,0.800000,19.000000,14.000000,15.000000,1.000000
50%,2011.0,500000.500000,1.000000,6.000000,41.000000,160.000000,60.000000,80.000000,1.000000,1.000000,...,108.00000,54.000000,111.000000,14.000000,1.000000,0.900000,22.000000,20.000000,23.000000,1.000000
75%,2011.0,750000.250000,2.000000,8.000000,44.000000,170.000000,70.000000,86.000000,1.200000,1.200000,...,161.00000,63.000000,134.000000,15.200000,1.000000,1.000000,28.000000,28.000000,39.000000,3.000000
max,2011.0,1000000.000000,2.000000,14.000000,49.000000,190.000000,125.000000,128.000000,9.900000,9.900000,...,999.00000,982.000000,2107.000000,24.900000,6.000000,98.000000,999.000000,999.000000,999.000000,3.000000

In [ ]:
dat2011.shape[1]

34

In [ ]:
dat2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 34 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   기준년도          1000000 non-null  int64
 1   가입자일련번호       1000000 non-null  int64
 2   성별코드          1000000 non-null  int64
 3   연령대코드(5세단위)   1000000 non-null  int64
 4   시도코드          1000000 non-null  int64
 5   신장(5Cm단위)     1000000 non-null  int64
 6   체중(5Kg 단위)    1000000 non-null  int64
 7   허리둘레          1000000 non-null  int64
 8   시력(좌)         999907 non-null   float64
 9   시력(우)         999897 non-null   float64
 10  청력(좌)         999882 non-null   float64
 11  청력(우)         999879 non-null   float64
 12  수축기혈압         1000000 non-null  int64
 13  이완기혈압         1000000 non-null  int64
 14  식전혈당(공복혈당)    1000000 non-null  int64
 15  총콜레스테롤        1000000 non-null  int64
 16  트리글리세라이드      1000000 non-null  int64
 17  HDL콜레스테롤      1000000 non-null  float64
 18  LDL콜레스테롤      989987 non-null   float64
 19  혈색소           1000000 non-null  float64
 20  요단백           995622 non-null   float64
 21  혈청크레아티닌       1000000 non-null  float64
 22  (혈청지오티)AST    1000000 non-null  int64
 23  (혈청지오티)ALT    1000000 non-null  int64
 24  감마지티피         1000000 non-null  int64
 25  흡연상태          999841 non-null   float64
 26  음주여부          999785 non-null   object
 27  구강검진 수검여부     1000000 non-null  object
 28  치아우식증유무       155208 non-null   object
 29  결손치유무         366828 non-null   object
 30  치아마모증유무       366827 non-null   object
 31  제3대구치(사랑니)이상  286823 non-null   object
 32  치석            366830 non-null   object
 33  데이터공개일자       1000000 non-null  object
dtypes: float64(10), int64(16), object(8)
memory usage: 259.4+ MB

In [ ]:
nulltable=dat2011.isnull().sum().to_frame('2011null_count') #각 변수들의 null값의 개수의 합을 to_frame함수를 이용해 표로 만들었다.
nulltable

              2011null_count
기준년도                       0
가입자일련번호                    0
성별코드                       0
연령대코드(5세단위)                0
시도코드                       0
신장(5Cm단위)                  0
체중(5Kg단위)                  0
허리둘레                       0
시력(좌)                      0
시력(우)                      0
청력(좌)                      0
청력(우)                      0
수축기혈압                      0
이완기혈압                      0
식전혈당(공복혈당)                 0
총콜레스테롤                     0
트리글리세라이드                   0
HDL콜레스테롤                   0
LDL콜레스테롤               10012
혈색소                        0
요단백                     4354
혈청크레아티닌                    0
(혈청지오티)AST                 0
(혈청지오티)ALT                 0
감마지티피                      0
흡연상태                       0
음주여부                       0
구강검진수검여부                   0
치아우식증유무               844421
결손치유무                 632910
치아마모증유무               632911
제3대구치(사랑니)이상          712849
치석                    632908

In [ ]:
nulltable['2012null_count'] = dat2012.isnull().sum()
nulltable['2013null_count'] = dat2013.isnull().sum()
nulltable['2014null_count'] = dat2014.isnull().sum()
nulltable['2015null_count'] = dat2015.isnull().sum()
nulltable['2016null_count'] = dat2016.isnull().sum()
nulltable['2017null_count'] = dat2017.isnull().sum()

In [ ]:
nulltable

,2011null_count,2012null_count,2013null_count,2014null_count,2015null_count,2016null_count,2017null_count
기준년도,0,0,0,0.0,0.0,0,0
가입자일련번호,0,0,0,0.0,0.0,0,0
성별코드,0,0,0,0.0,0.0,0,0
연령대코드(5세단위),0,0,0,0.0,0.0,0,0
시도코드,0,0,0,0.0,0.0,0,0
신장(5Cm단위),0,0,0,0.0,0.0,0,0
체중(5Kg단위),0,0,0,0.0,0.0,0,0
허리둘레,0,0,0,0.0,0.0,0,0
시력(좌),0,0,0,0.0,0.0,0,0
시력(우),0,0,0,0.0,0.0,0,0
청력(좌),0,0,0,0.0,0.0,0,0
청력(우),0,0,0,0.0,0.0,0,0
수축기혈압,0,0,0,0.0,0.0,0,0
이완기혈압,0,0,0,0.0,0.0,0,0
식전혈당(공복혈당),0,0,0,0.0,0.0,0,0
총콜레스테롤,0,0,0,0.0,0.0,0,0
트리글리세라이드,0,0,0,0.0,0.0,0,0
HDL콜레스테롤,0,0,0,0.0,0.0,0,0
LDL콜레스테롤,10012,10980,5383,4241.0,3189.0,2583,2867
혈색소,0,0,0,0.0,0.0,0,0
요단백,4354,4408,4348,4310.0,4516.0,4797,4545
혈청크레아티닌,0,0,0,0.0,0.0,0,0
(혈청지오티)AST,0,0,0,0.0,0.0,0,0
(혈청지오티)ALT,0,0,0,0.0,0.0,0,0
감마지티피,0,0,0,0.0,0.0,0,0
흡연상태,0,0,0,0.0,0.0,0,0
음주여부,0,0,0,0.0,0.0,998406,0
구강검진수검여부,0,0,0,0.0,0.0,0,0
치아우식증유무,844421,615024,615944,888636.0,894191.0,998406,998752
결손치유무,632910,615023,615944,NaN,NaN,998406,998752
치아마모증유무,632911,615022,615944,NaN,NaN,998406,998752
제3대구치(사랑니)이상,712849,615027,615944,NaN,NaN,998406,998752
치석,632908,615028,615944,616512.0,618098.0,618850,620667

연도별 데이터 개수

In [ ]:
print("2011 : ",dat2011.shape[0],
      "\n2012 : ",dat2012.shape[0],
      "\n2013 : ",dat2013.shape[0],
      "\n2014 : ",dat2014.shape[0],
      "\n2015 : ",dat2015.shape[0],
      "\n2016 : ",dat2016.shape[0],
      "\n2017 : ",dat2017.shape[0])

2011 :  1000000
2012 :  1000000
2013 :  1000000
2014 :  1000000
2015 :  1000000
2016 :  1000000
2017 :  1000000

연도별 변수 개수 확인

In [ ]:
print("2011 : ",dat2011.shape[1],
      "\n2012 : ",dat2012.shape[1],
      "\n2013 : ",dat2013.shape[1],
      "\n2014 : ",dat2014.shape[1],
      "\n2015 : ",dat2015.shape[1],
      "\n2016 : ",dat2016.shape[1],
      "\n2017 : ",dat2017.shape[1])

2011 :  34
2012 :  34
2013 :  36
2014 :  31
2015 :  31
2016 :  34
2017 :  34

In [ ]:
dat2011.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,감마지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,결손치유무,치아마모증유무,제3대구치(사랑니)이상,치석,데이터공개일자
0,2011,762544,2,1,47,145,40,66,1.2,1.2,...,13,1.0,Y,Y,NaN,N,N,N,N,2015-12-20
1,2011,56745,2,1,26,145,45,68,0.9,1.0,...,12,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20
2,2011,171067,2,1,26,145,45,65,1.0,1.5,...,16,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20
3,2011,196496,2,1,27,145,45,68,0.9,0.9,...,23,1.0,N,Y,NaN,N,N,N,N,2015-12-20
4,2011,812525,2,1,46,150,35,56,0.7,0.9,...,8,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20

In [ ]:
dat2012.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,감마지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,결손치유무,치아마모증유무,제3대구치(사랑니)이상,치석,데이터공개일자
0,2012,220721,2,14,46,150,45,72,0.2,0.4,...,11,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20
1,2012,830677,2,14,45,145,30,68,0.1,0.1,...,11,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20
2,2012,978884,1,1,26,140,40,68,0.4,0.6,...,25,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20
3,2012,918718,2,1,11,140,40,66,0.7,0.6,...,12,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20
4,2012,922362,2,1,28,140,40,77,0.6,0.4,...,24,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20

In [ ]:
dat2013.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,음주여부,구강검진 수검여부,치아우식증유무,결손치유무,치아마모증유무,제3대구치(사랑니)이상,치석,데이터공개일자,Unnamed: 34,Unnamed: 35
0,2013,24193,2,14,11,145,35,83,0.1,0.1,...,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20,NaN,NaN
1,2013,134496,1,1,27,140,35,68,0.8,0.8,...,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20,NaN,NaN
2,2013,978782,2,1,29,145,35,68,9.9,9.9,...,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20,NaN,NaN
3,2013,10313,2,1,43,145,40,62,1.0,1.0,...,N,Y,Y,N,N,N,N,2015-12-20,NaN,NaN
4,2013,915645,2,1,41,145,40,64,0.8,0.7,...,N,N,NaN,NaN,NaN,NaN,NaN,2015-12-20,NaN,NaN

In [ ]:
dat2014.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석유무,데이터 기준일자
0,2014,1,1,6,42,180,75,79,1.5,1.2,...,1.2,31,18,23,3.0,N,Y,N,N,2016-12-20
1,2014,2,2,18,41,150,65,79,0.1,0.1,...,0.8,11,4,15,1.0,Y,N,NaN,NaN,2016-12-20
2,2014,3,1,12,41,170,70,95,0.8,1.0,...,0.6,138,73,112,3.0,Y,Y,N,Y,2016-12-20
3,2014,4,2,11,41,165,80,104,0.8,0.2,...,0.9,19,14,21,1.0,N,Y,N,Y,2016-12-20
4,2014,5,1,6,44,175,75,81,1.5,1.5,...,1.0,32,39,98,1.0,Y,Y,NaN,Y,2016-12-20

In [ ]:
dat2015.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석유무,데이터 기준일자
0,2015,1,2,15,45,155,60,88,0.6,0.7,...,1.1,17,28,23,1.0,Y,N,NaN,NaN,2016-12-20
1,2015,2,2,15,11,155,65,98,1.2,0.6,...,1.0,25,30,41,1.0,Y,Y,NaN,N,2016-12-20
2,2015,3,2,11,26,155,65,85,1.2,0.9,...,0.6,18,16,25,1.0,N,N,NaN,NaN,2016-12-20
3,2015,4,1,9,41,175,75,89,0.2,0.2,...,0.9,28,40,50,1.0,Y,Y,N,NaN,2016-12-20
4,2015,5,1,16,47,160,50,78,0.5,0.6,...,1.0,20,13,19,2.0,N,Y,NaN,N,2016-12-20

In [ ]:
dat2016.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),...,감마지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,결손치유무,치아마모증유무,제3대구치(사랑니)이상,치석,데이터공개일자
0,2016,1,1,10,27,175.0,75.0,86.0,1.0,1.2,...,45.0,3.0,NaN,N,NaN,NaN,NaN,NaN,NaN,2017-12-19
1,2016,2,2,11,41,160.0,65.0,85.0,1.5,1.2,...,19.0,1.0,NaN,N,NaN,NaN,NaN,NaN,NaN,2017-12-19
2,2016,3,2,11,43,150.0,55.0,80.0,1.5,1.5,...,64.0,1.0,NaN,N,NaN,NaN,NaN,NaN,NaN,2017-12-19
3,2016,4,1,12,48,175.0,70.0,85.0,1.2,1.2,...,69.0,2.0,NaN,Y,NaN,NaN,NaN,NaN,Y,2017-12-19
4,2016,5,2,6,11,160.0,50.0,67.0,0.4,0.5,...,20.0,1.0,NaN,N,NaN,NaN,NaN,NaN,NaN,2017-12-19

In [ ]:
dat2017.head()

,기준년도,가입자일련번호,성별코드,연령대코드(5세단위),시도코드,신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),...,감마지티피,흡연상태,음주여부,구강검진수검여부,치아우식증유무,결손치유무,치아마모증유무,제3대구치(사랑니)이상,치석,데이터공개일자
0,2017,1,1,8,43,170,75,90.0,1.0,1.0,...,40.0,1.0,Y,Y,NaN,NaN,NaN,NaN,Y,2018-11-26
1,2017,2,1,7,11,180,80,89.0,0.9,1.2,...,27.0,3.0,N,Y,NaN,NaN,NaN,NaN,NaN,2018-11-26
2,2017,3,1,9,41,165,75,91.0,1.2,1.5,...,68.0,1.0,N,N,NaN,NaN,NaN,NaN,NaN,2018-11-26
3,2017,4,1,11,48,175,80,91.0,1.5,1.2,...,18.0,1.0,N,Y,NaN,NaN,NaN,NaN,N,2018-11-26
4,2017,5,1,11,30,165,60,80.0,1.0,1.2,...,25.0,1.0,N,Y,NaN,NaN,NaN,NaN,N,2018-11-26